### ISSUE TITLE
Change disk usage plot to a pie chart or a disk chart. 

### ISSUE THREAD

**Issue by ajinsunny** [yoobool/flask-state#25]
**Is your feature request related to a problem? Please describe.**
Change disk usage plot to a pie chart or a disk chart. 

**Describe the solution you'd like**
The disk usage plot can be changed to a pie chart which will have a better representation.

**Comment by FesonX** [comment]
@ajinsunny Good first issue, may be a **bar chart** like iOS or Android in the settings of storage will be better?<br>

**Comment by ajinsunny** [comment]
Thanks @FesonX :)
