### ISSUE TITLE
add network piece

### ISSUE THREAD

**Issue by bitbytes01** [yoobool/flask-state#26]
Could you add a network piece. Like "netstat  with set or select key word arguments. That tie back to process id too.

This would be helpful, when I'm troubleshooting process that tie back to sockets... And maybe resolve the IP to country of origin.

**Comment by FesonX** [comment]
@bitbytes01 Would you describe the feature you proposed more detailed?<br>

Like this: 
> I want to detect which process the socket tie back to, its running path, its state via `netstat`
