### ISSUE TITLE
`name` field is duplicated in both setup.py and setup.cfg

### ISSUE THREAD

**Issue by sobolevn** [yoobool/flask-state#28]
1. https://github.com/yoobool/flask-state/blob/master/setup.cfg#L2
2. https://github.com/yoobool/flask-state/blob/master/setup.py#L8

In my opinion, there should be only a single place to define this data.

**Comment by XiaoyueCai** [comment]
@sobolevn Thanks, we will fix it in the next version.

**Comment by aaajiulong** [comment]
Fixed by [`31f331dd`](https://github.com/yoobool/flask-state/commit/31f331dd5f902758eb3316848216ec10660e8b46).
