### ISSUE TITLE
Example needs a separate README

### ISSUE THREAD

**Issue by sobolevn** [yoobool/flask-state#29]
Currently, it is unclear how to use `example/`, because there's no information available.

Looks like it needs its own guide: 
- How to install all the required dependencies?
- How to run the project?
- What should you expect?
- How to simulate the high-load so I can test that the metrics work?

**Comment by aaajiulong** [comment]
Thanks, we will implement the suggestions you mentioned above as soon as possible.

**Comment by FesonX** [comment]
Pull request has been proposed #30
