### ISSUE TITLE
Consider using dataclasses

### ISSUE THREAD

**Issue by adsharma** [yoobool/flask-state#37]
I see that you're using sqlalchemy and db.Model to describe your data and queries.

I've been trying to use dataclasses + fquery to do something similar.

dataclasses-sql on sqlalchemy:  most recent commits in the repo below have examples.

https://github.com/adsharma/dataclasses-sql/tree/decorator

More on fquery:

https://adsharma.github.io/fquery/
https://github.com/adsharma/fquery

Looking for django/flask projects to test these ideas out.

**Comment by adsharma** [comment]
https://github.com/adsharma/dataclasses-sql/commits/upsert has one extra commit demonstrating writes.

**Comment by FesonX** [comment]
@adsharma Though the project has wonderful async feature, **it looks like a experimental project**. <br>
I think it's not suitable for using this project for major tech stack now.<br>
Thank you for introduce this project for us.

**Comment by FesonX** [comment]
@adsharma BTW, AsyncIO is introduced in [SQLAlchemy 1.4](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html), maybe we will try this feature in our develop branch :p

**Comment by adsharma** [comment]
Yes definitely recommend async with sqlalchemy. Also see dataclasses and
the sql integration
