### ISSUE TITLE
Chart titles only display "Today" regardless of interval

### ISSUE THREAD

**Issue by skekre98** [yoobool/flask-state#38]
**Describe the bug**
Regardless of what interval is set(1,3,7,30), the charts are always titled "Today" in the preview web app.

**To Reproduce**
1. Go to https://flask-state.herokuapp.com/
2. Click on **preview**
3. Select [3, 7, or 30] days for your interval
4. Notice that the charts still display **Today**

**Expected behavior**
I'm guessing this should be dynamic based on the intervals.

**Screenshots**
![Screen Shot 2020-12-22 at 2 48 10 PM](https://user-images.githubusercontent.com/18124349/102940524-601f9400-4465-11eb-897a-6eb4f0ee56f9.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chome
 - Version: 1.0.5

**Additional context**
n/a

**Comment by aaronxiongli** [comment]
@skekre98 Thanks for your advice, we will fix this bug on future version asap.
