### ISSUE TITLE
Network monitor on web dashboard

### ISSUE THREAD

**Issue by skekre98** [yoobool/flask-state#39]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be nice to have a network monitor in the dashboard. Something that depicted network information such as packets in/out, data received/sent, etc.

**Describe alternatives you've considered**
No alternative, but I think it would make a good addition to the dashboard.

**Additional context**
Might I recommend looking into the [Scapy](https://scapy.readthedocs.io/en/latest/introduction.html) python library. It is a packet manipulation library that allows you to implement packet sniffers and network monitors.

**Comment by aaajiulong** [comment]
@skekre98 Thanks, network monitor is in our road map.
