### ISSUE TITLE
The Readme file is difficult to understand the exactully process of running .Could you guys make it much easier for beginners?

### ISSUE THREAD

**Issue by boxionghuang** [yoobool/flask-state#40]
null

**Comment by boxionghuang** [comment]
null

**Comment by FesonX** [comment]
@boxionghuang Hi, thank you for using Flask-State, We will consider optimize README. <br>
Before we optimize, you can checkout `examples` directory for another HOW-TO document and a simple self-contained exmaple :P <br>
