### ISSUE TITLE
Memory usage of the application or the code

### ISSUE THREAD

**Issue by Prashantmdgl9** [yoobool/flask-state#46]
Real time use of the memory in the code
e.g. if you import NumPy then what's the state of the memory. If you create a variable then how much did the memory increase.
Increase or change in memory usage as per every line that's present in the code would be really helpful for the programmers.

**Comment by FesonX** [comment]
@Prashantmdgl9 Thanks for ur advice, **this feature it's not in Flask-State's roadmap now**.<br>
Try [memory_profiler](https://github.com/pythonprofilers/memory_profiler.git) or [objgraph](https://github.com/mgedmin/objgraph.git) instead
